In [24]:
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [25]:
# load apple watch data
comedy_aw = pd.read_csv('generated_data/comedy_aw.csv')
documentary_aw = pd.read_csv('generated_data/documentary_aw.csv')
horror_aw = pd.read_csv('generated_data/horror_aw.csv')

# load tracked motion data
comedy_tm = pd.read_csv('generated_data/comedy_tm.csv')
documentary_tm = pd.read_csv('generated_data/documentary_tm.csv')
horror_tm = pd.read_csv('generated_data/horror_tm.csv')

# load pupil size data
comedy_ps = pd.read_csv('generated_data/comedy_ps.csv')
documentary_ps = pd.read_csv('generated_data/documentary_ps.csv')
horror_ps = pd.read_csv('generated_data/horror_ps.csv')

In [26]:
def merge_dataframes(aw_df, tm_df, ps_df):
    # Convert to datetime
    aw_df['timestamp'] = pd.to_datetime(aw_df['timestamp']).dt.tz_localize(None)
    tm_df['timestamp'] = pd.to_datetime(tm_df['timestamp']).dt.tz_localize(None)
    ps_df['timestamp'] = pd.to_datetime(ps_df['timestamp']).dt.tz_localize(None)
    
    # Sort all DataFrames 
    aw = aw_df.sort_values('timestamp')
    tm = tm_df.sort_values('timestamp')
    ps = ps_df.sort_values('timestamp')
    
    # Merge on nearest time
    merged = pd.merge(aw, tm, on='timestamp', how='inner')
    return pd.merge(merged, ps, on='timestamp', how='inner')

In [27]:
comedy = merge_dataframes(comedy_aw, comedy_tm, comedy_ps)
documentary = merge_dataframes(documentary_aw, documentary_tm, documentary_ps)
horror = merge_dataframes(horror_aw, horror_tm, horror_ps)

In [28]:
comedy

,timestamp,active_energy_burned,basal_energy_burned,heart_rate,physical_effort,x_coordinate,y_coordinate,pupil_diameter_mm,iris_diameter_mm,pupil_iris_ratio,overall_confidence,pupil_circularity,gaze_direction,pupil_detected,iris_detected
0,2025-06-05 16:25:55,NaN,NaN,62.0,NaN,409.206897,194.000000,0.000000,11.8,0.000000,0.463664,0.649469,Center,True,False
1,2025-06-05 16:25:56,0.077,0.066,NaN,NaN,413.433333,194.800000,0.000000,11.8,0.000000,0.464653,0.619537,Center,True,False
2,2025-06-05 16:25:59,0.077,0.066,60.0,NaN,397.333333,191.000000,0.000000,11.8,0.000000,0.253074,0.337432,Center,True,False
3,2025-06-05 16:26:01,0.077,0.066,NaN,NaN,397.166667,190.600000,0.000000,11.8,0.000000,0.272663,0.363550,Center,True,False
4,2025-06-05 16:26:04,0.077,0.066,NaN,NaN,391.000000,189.333333,2.602941,11.8,0.220588,0.413849,0.392842,Up-Right,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,2025-06-05 16:56:13,0.077,0.066,62.0,NaN,335.866667,207.000000,0.000000,11.8,0.000000,0.497016,0.710121,Center,True,False
946,2025-06-05 16:56:15,0.077,0.066,NaN,NaN,348.233333,203.666667,0.000000,11.8,0.000000,0.360245,0.480327,Center,True,False
947,2025-06-05 16:56:18,0.077,0.066,67.0,NaN,344.033333,205.866667,0.000000,11.8,0.000000,0.385128,0.513503,Center,True,False
948,2025-06-05 16:56:20,0.077,0.066,NaN,6.5,345.866667,205.033333,0.000000,11.8,0.000000,0.248906,0.331875,Center,True,False
949,2025-06-05 16:56:23,0.129,0.066,NaN,NaN,347.933333,201.066667,0.000000,11.8,0.000000,0.280486,0.373982,Center,True,False

In [29]:
documentary

,timestamp,active_energy_burned,basal_energy_burned,heart_rate,physical_effort,x_coordinate,y_coordinate,pupil_diameter_mm,iris_diameter_mm,pupil_iris_ratio,overall_confidence,pupil_circularity,gaze_direction,pupil_detected,iris_detected
0,2025-06-05 17:13:30,0.077,0.066,60.0,NaN,355.533333,225.700000,0.000000,11.8,0.000000,0.248222,0.330963,Center,True,False
1,2025-06-05 17:13:33,0.097,0.066,60.0,5.4,360.933333,223.600000,0.000000,11.8,0.000000,0.309581,0.412775,Center,True,False
2,2025-06-05 17:13:35,0.097,0.066,NaN,NaN,350.700000,222.400000,0.000000,11.8,0.000000,0.363035,0.484047,Center,True,False
3,2025-06-05 17:13:38,0.097,0.066,NaN,NaN,344.766667,225.600000,0.000000,11.8,0.000000,0.327034,0.436045,Center,True,False
4,2025-06-05 17:13:40,0.097,0.066,59.0,NaN,347.758621,228.000000,0.000000,11.8,0.000000,0.333728,0.444971,Center,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,2025-06-05 17:43:59,0.077,0.066,57.0,NaN,342.800000,269.766667,0.000000,11.8,0.000000,0.282593,0.376791,Center,True,False
952,2025-06-05 17:44:02,0.077,0.066,60.0,6.5,359.933333,279.433333,0.000000,11.8,0.000000,0.295276,0.393701,Center,True,False
953,2025-06-05 17:44:05,0.099,0.066,NaN,NaN,360.258065,283.580645,1.198438,11.8,0.101562,0.470213,0.458448,Right,True,True
954,2025-06-05 17:44:07,0.155,0.066,NaN,NaN,361.233333,283.233333,0.000000,11.8,0.000000,0.345671,0.460895,Center,True,False
955,2025-06-05 17:44:10,0.155,0.066,73.0,2.5,360.000000,284.000000,1.229167,11.8,0.104167,0.382587,0.351414,Down-Right,True,True

In [30]:
horror

,timestamp,active_energy_burned,basal_energy_burned,heart_rate,physical_effort,x_coordinate,y_coordinate,pupil_diameter_mm,iris_diameter_mm,pupil_iris_ratio,overall_confidence,pupil_circularity,gaze_direction,pupil_detected,iris_detected
0,2025-06-05 17:58:54,0.077,0.066,56.0,NaN,374.935484,244.000000,0.0,11.8,0.0,0.317583,0.423444,Center,True,False
1,2025-06-05 17:58:56,0.077,0.066,NaN,NaN,371.965517,243.000000,0.0,11.8,0.0,0.436879,0.582505,Center,True,False
2,2025-06-05 17:58:59,0.077,0.066,NaN,NaN,366.620690,236.068966,0.0,11.8,0.0,0.430969,0.613296,Center,True,False
3,2025-06-05 17:59:00,NaN,NaN,54.0,NaN,359.833333,239.500000,0.0,11.8,0.0,0.285978,0.381305,Center,True,False
4,2025-06-05 17:59:01,0.077,0.066,NaN,NaN,359.433333,239.000000,0.0,11.8,0.0,0.254932,0.339909,Center,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,2025-06-05 18:27:09,0.077,0.066,56.0,NaN,303.400000,225.000000,0.0,11.8,0.0,0.366368,0.488491,Center,True,False
876,2025-06-05 18:27:12,0.077,0.066,NaN,NaN,302.866667,225.000000,0.0,11.8,0.0,0.270445,0.360594,Center,True,False
877,2025-06-05 18:27:15,0.070,0.066,NaN,NaN,302.833333,225.466667,0.0,11.8,0.0,0.334241,0.445655,Center,True,False
878,2025-06-05 18:27:16,NaN,NaN,53.0,NaN,302.533333,225.200000,0.0,11.8,0.0,0.312355,0.416473,Center,True,False
879,2025-06-05 18:27:17,0.070,0.066,NaN,5.0,303.000000,225.000000,0.0,11.8,0.0,0.366722,0.488962,Center,True,False

In [31]:
# Add genre column
comedy['genre'] = 'comedy'
documentary['genre'] = 'documentary'
horror['genre'] = 'horror'

# Concatenate all
df_all = pd.concat([comedy, documentary, horror], ignore_index=True)

In [32]:
df_all

,timestamp,active_energy_burned,basal_energy_burned,heart_rate,physical_effort,x_coordinate,y_coordinate,pupil_diameter_mm,iris_diameter_mm,pupil_iris_ratio,overall_confidence,pupil_circularity,gaze_direction,pupil_detected,iris_detected,genre
0,2025-06-05 16:25:55,NaN,NaN,62.0,NaN,409.206897,194.000000,0.000000,11.8,0.000000,0.463664,0.649469,Center,True,False,comedy
1,2025-06-05 16:25:56,0.077,0.066,NaN,NaN,413.433333,194.800000,0.000000,11.8,0.000000,0.464653,0.619537,Center,True,False,comedy
2,2025-06-05 16:25:59,0.077,0.066,60.0,NaN,397.333333,191.000000,0.000000,11.8,0.000000,0.253074,0.337432,Center,True,False,comedy
3,2025-06-05 16:26:01,0.077,0.066,NaN,NaN,397.166667,190.600000,0.000000,11.8,0.000000,0.272663,0.363550,Center,True,False,comedy
4,2025-06-05 16:26:04,0.077,0.066,NaN,NaN,391.000000,189.333333,2.602941,11.8,0.220588,0.413849,0.392842,Up-Right,True,True,comedy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2781,2025-06-05 18:27:09,0.077,0.066,56.0,NaN,303.400000,225.000000,0.000000,11.8,0.000000,0.366368,0.488491,Center,True,False,horror
2782,2025-06-05 18:27:12,0.077,0.066,NaN,NaN,302.866667,225.000000,0.000000,11.8,0.000000,0.270445,0.360594,Center,True,False,horror
2783,2025-06-05 18:27:15,0.070,0.066,NaN,NaN,302.833333,225.466667,0.000000,11.8,0.000000,0.334241,0.445655,Center,True,False,horror
2784,2025-06-05 18:27:16,NaN,NaN,53.0,NaN,302.533333,225.200000,0.000000,11.8,0.000000,0.312355,0.416473,Center,True,False,horror
2785,2025-06-05 18:27:17,0.070,0.066,NaN,5.0,303.000000,225.000000,0.000000,11.8,0.000000,0.366722,0.488962,Center,True,False,horror

In [34]:
df_all.to_csv('generated_data/all_genres.csv', index=False)